name: 'Issue chat'
description: 'issue chat'
author: 'Tresre'
branding:
  icon: 'message-square'
  color: 'black'
inputs:
  token:
    description: 'Github_token'
    default: ${{ github.token }}
runs:
  using: node12
  main: 'lib/main.js'
