name: Chat

on:
  issue_comment:
    types: [created]
  issues:
    types: [created]

jobs:
  chat:
    name: Process Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process Label
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
