name: Chat

on: [issues]

jobs:
  chat:
    name: Process Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Response
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
