name: Chat

on:
  issue_comment:
    types: [created]
  issues:
    types: [created]

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - uses: Tresre/l@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
